research_task:
  description: >
    Search the web for high-quality hands-on blogs about the latest AWS developments focused on {topic}.
    Prioritize blogs that include code examples, tutorials, and real-world implementations rather than marketing materials.
    The current year is {current_year}, so only include up-to-date sources.
  expected_output: >
    A list of 10 high-quality AWS blog posts with:
      - Blog title
      - Summary of key insights
      - Link to the original article
  agent: aws_researcher

writing_task:
  description: >
    Create a professional, hands-on tutorial based on the findings. 
    The article must be written for the blog **awsdesdecero.com**, and it should have an **amigo** and **practical** tone. 
    The article must be written in **Spanish (Spain)**, in the first person, and should avoid the use of Latin American terms or expressions.
    Include clear explanations, step-by-step guides, and working AWS code examples. 
    Ensure the tutorial is technically accurate, useful for AWS developers, and follows best practices.
  expected_output: >
    A full-length AWS tutorial with:
      - Introduction
      - Explanation of the AWS feature(s) covered
      - Step-by-step implementation guide
      - Code snippets (Python, AWS CLI, or Terraform where applicable)
      - Best practices & common pitfalls
  agent: technical_writer

formatting_task:
  description: >
    Convert the tutorial into professionally formatted HTML.
    Ensure proper use of <h1>, <h2>, <p>, <code>, and other elements for clarity and readability.
    Add a friendly and engaging tone, making it accessible to AWS enthusiasts at different levels. 
    Keep the Spanish (Spain) localization in the writing, maintaining the voice of the article consistent with a friendly and conversational style.
  expected_output: >
    A fully formatted HTML document ready for publication, including:
      - Styled headers (<h1>, <h2>)
      - Code blocks (<pre><code>)
      - Lists (<ul>, <ol>)
      - Proper paragraph spacing (<p>)
  agent: content_formatter
